---
- name: applying Ubuntu cloud baseline
  hosts: all
  gather_facts: yes
  become: yes

  tasks:
    - name: update all packages
      apt:
        name: "*"
        update_cache: yes
        state: latest

    - name: install base packages
      apt:
        name:
          - htop
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - git
          - pwgen
          - wget
          - net-tools
          - nmap
          - tcpdump
          - wireguard
          - ldnsutils
          - whois
          - geoip-bin
        update_cache: yes
        state: latest

    - name: clone nano syntax repo
      git:
        clone: yes
        dest: /usr/share/nano-syntax-highlighting/
        repo: https://github.com/scopatz/nanorc.git

    - name: include nano syntax in nanorc
      command:
        cmd: 'echo "include /usr/share/nano-syntax-highlighting/*.nanorc" >> /etc/nanorc'

...
